PRAGMA FOREIGN_KEY = ON;

DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS List;

CREATE TABLE List(
    uuid VARCHAR(30) PRIMARY KEY,
    title VARCHAR(30) NOT NULL
);

CREATE TABLE Item(
    uuid VARCHAR(30) PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    quantity INTEGER NOT NULL,
    list_uuid INTEGER NOT NULL,
    FOREIGN KEY(list_uuid) REFERENCES List(uuid)
);
