PRAGMA FOREIGN_KEY = ON;

DROP TABLE IF EXISTS UserList;
DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS List;
DROP TABLE IF EXISTS Users;

CREATE TABLE Users(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(20) UNIQUE NOT NULL,
    password VARCHAR(20) NOT NULL
);

CREATE TABLE List(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(30) NOT NULL
);

CREATE TABLE Item(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(30) NOT NULL,
    quantity INTEGER NOT NULL,
    list_id INTEGER NOT NULL,
    FOREIGN KEY(list_id) REFERENCES List(id)
);

CREATE TABLE UserList(
    user_id INTEGER NOT NULL,
    list_id INTEGER NOT NULL,
    PRIMARY KEY(user_id, list_id),
    FOREIGN KEY(user_id) REFERENCES User(id),
    FOREIGN KEY(list_id) REFERENCES List(id)
);

INSERT INTO List(title) VALUES('Grocery List');